# Generated by Django 5.1.7 on 2025-03-22 12:53

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('artist_id', models.CharField(max_length=24)),
                ('release_date', models.DateField()),
                ('status', models.IntegerField()),
                ('image', models.URLField()),
            ],
            options={
                'db_table': 'albums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('user1_id', models.CharField(max_length=24)),
                ('user2_id', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=24)),
                ('sender_id', models.CharField(max_length=24)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=24)),
                ('song_id', models.CharField(max_length=24)),
                ('purchase_date', models.DateField()),
            ],
            options={
                'db_table': 'purchases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('status', models.IntegerField()),
                ('artists', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=24), size=None)),
                ('categories', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=24), size=None)),
                ('file_url', models.URLField()),
                ('price', models.IntegerField()),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('album_id', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('avatar', models.URLField(blank=True)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
