# Generated by Django 5.1.7 on 2025-03-26 07:34

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('user_id', models.CharField(max_length=24)),
                ('status', models.IntegerField()),
                ('songs', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=24), size=None)),
            ],
            options={
                'db_table': 'playlists',
                'managed': False,
            },
        ),
    ]
